# Welcome to Denis Ndemwa!

# Site settings
title: Denis Ndemwa
email: kyalodenis@gmail.com
description: "Electrical & Electronics Engineer | Researcher | Consultant — Passionate about designing and developing innovative hardware and embedded systems."
twitter_username: DenisNdemwa
github_username: ND3MW4

# Theme skin
# options: air, aqua, contrast, dark, dirt, neon, mint, plum, sunrise
minimal_mistakes_skin: neon

search: true

remote_theme: mmistakes/minimal-mistakes
markdown: kramdown
paginate: 3
paginate_path: /page:num/

include:
  - _pages

plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed
  - jemoji
  - jekyll-include-cache

author:
  name   : "Denis Ndemwa"
  avatar : "/assets/images/photo.jpg"
  bio    : "Inventing at the intersection of circuits, code, and intelligent systems."
  links:
    - label: "LinkedIn"
      icon: "fab fa-fw fa-linkedin"
      url: "https://www.linkedin.com/in/denisndemwa/"
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/ND3MW4"
    - label: "Email"
      icon: "fas fa-fw fa-envelope"
      url: "mailto:kyalodenis@gmail.com"
    - label: "Call"
      icon: "fas fa-fw fa-phone"
      url: "tel:+254710425528"
    - label: "X"
      icon: "fab fa-fw fa-twitter-square"
      url: "https://x.com/DenisNdemwa"
    - label: "Instagram"
      icon: "fab fa-fw fa-instagram"
      url: "https://instagram.com/ndemwah"

footer:
  links:
    - label: "LinkedIn"
      icon: "fab fa-fw fa-linkedin"
      url: "https://www.linkedin.com/in/denisndemwa/"
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/ND3MW4"
    - label: "Email"
      icon: "fas fa-fw fa-envelope"
      url: "mailto:kyalodenis@gmail.com"
    - label: "Call"
      icon: "fas fa-fw fa-phone"
      url: "tel:+254710425528"
    - label: "X"
      icon: "fab fa-fw fa-twitter-square"
      url: "https://x.com/DenisNdemwa"
    - label: "Instagram"
      icon: "fab fa-fw fa-instagram"
      url: "https://instagram.com/ndemwah"

defaults:
  - scope:
      path: ""
      type: posts
    values:
      layout: single
      author_profile: true
      read_time: true
      comments: true
      share: true
      related: true

  - scope:
      path: "_pages"
      type: pages
    values:
      layout: single
      author_profile: true

category_archive:
  type: liquid
  path: /Categories/

tag_archive:
  type: liquid
  path: /tags/
