# Welcome to Denis Ndemwa!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that.

title: Denis Ndemwa
email: kyalodeins@gmail.com
description: >-
  Electrical & Electronics Engineer | Data & AI Explorer | Turning hardware into intelligent systems
twitter_username: DenisNdemwa
github_username: ND3MW4
minimal_mistakes_skin: neon # "air", "aqua", "contrast", "dark", "dirt", "neon", "mint", "plum", "sunrise"
search: true

# Build settings
markdown: kramdown
remote_theme: mmistakes/minimal-mistakes

# Outputting
permalink: /:categories/:title/
paginate: 3
paginate_path: /page:num/
timezone: # optional, e.g., "Africa/Nairobi"

include:
  - _pages

# Plugins
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed
  - jemoji
  - jekyll-include-cache

author:
  name   : "Denis Ndemwa"
  avatar : "/assets/images/photo.jpg"
  bio    : "Inventing at the Intersection of Circuits, Code, and Data Intelligence"
  links:
    - label: "Website"
      icon: "fas fa-fw fa-link"
      url: "https://"
    - label: "X"
      icon: "fab fa-fw fa-twitter-square"
      url: "https://x.com/DenisNdemwa"
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/ND3MW4"
    - label: "Instagram"
      icon: "fab fa-fw fa-instagram"
      url: "https://instagram.com/ndemwah"

footer:
  links:
    - label: "LinkedIn"
      icon: "fab fa-linkedin"
      url: "https://www.linkedin.com/in/denisndemwa/"
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/ND3MW4"

defaults:
  - scope:
      path: ""
      type: posts
    values:
      layout: single
      author_profile: true
      read_time: true
      comments: true
      share: true
      related: true

  - scope:
      path: "_pages"
      type: pages
    values:
      layout: single
      author_profile: true

category_archive:
  type: liquid
  path: /categories/

tag_archive:
  type: liquid
  path: /tags/
